repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-added-large-files
  - id: check-json
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: jshint
    name: jshint
    entry: npx jshint
    language: system
    types: [javascript]
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
