name: test
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: devcontainers/ci@v0.2
      with:
        cacheFrom: ghcr.io/wowless/byobcdn-devcontainer
        imageName: ghcr.io/wowless/byobcdn-devcontainer
        refFilterForPush: refs/heads/main
        runCmd: pre-commit run -a
